# Site settings

title: Your awesome title

email: your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  This is the official blog for the “Between | Screens” micropodcast.
  It contains mainly posts that summarize the release of new episodes. Enjoy!

baseurl: '/between_blog'

url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: betweenscreens_

#github_username:  jekyll

# Build settings
markdown: kramdown
