# Site settings

title: "| Blog"  

email: your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  Official blog for the “Between | Screens” micropodcast.
  It contains mainly posts that summarize the release of new episodes. Enjoy!

paginate: 5
paginate_path: "/page/:num"

permalink: pretty
relative_permalinks: true

#baseurl: 'http://betweenpipes.com'
baseurl: ''

#url: "http://betweenpipes.com" # the base hostname & protocol for your site
url: "http://localhost:4000/" # the base hostname & protocol for your site

twitter_username: betweenscreens_

#github_username:  jekyll

# Build settings
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass
